image: alpine:latest

pages:
  stage: deploy
  script:
  - echo 'Gathering the list...'
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - master
